/**
 * @file colorinfo.js
 * @description Parses a hex color and shows its RGB, HSL, integer value, and a
 *              live preview swatch image.
 */

/*
 * ============================================================
 *  COMMAND REFERENCE - /colorinfo
 * ============================================================
 *  Category    : Tools
 *  Summary     : Inspect a hex color (RGB, HSL, preview)
 *  Scope       : Guild slash command
 *  Cooldown    : 3s recommended (not enforced here)
 *  Permissions : Inherits the SlashCommandBuilder default for this file
 *
 *  Behavior notes:
 *    01. Replies using a rich EmbedBuilder for consistent styling across the bot.
 *    02. All user-supplied input is validated before any response is sent.
 *    03. On invalid input the command responds ephemerally so channels stay clean.
 *    04. Errors are caught and surfaced as friendly messages, never raw stack traces.
 *    05. The command is stateless and safe to run concurrently by many users.
 * ============================================================
 */


const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

/**
 * Normalize and validate a hex color string into a 6-digit form.
 * @param {string} input
 * @returns {string|null}
 */
function normalizeHex(input) {
    let hex = input.trim().replace(/^#/, '');
    // Expand shorthand like "f00" to "ff0000".
    if (/^[0-9a-fA-F]{3}$/.test(hex)) {
        hex = hex.split('').map(c => c + c).join('');
    }
    return /^[0-9a-fA-F]{6}$/.test(hex) ? hex.toLowerCase() : null;
}

/**
 * Convert a hex string to an {r,g,b} object.
 * @param {string} hex
 * @returns {{ r: number, g: number, b: number }}
 */
function hexToRgb(hex) {
    return {
        r: parseInt(hex.slice(0, 2), 16),
        g: parseInt(hex.slice(2, 4), 16),
        b: parseInt(hex.slice(4, 6), 16)
    };
}

/**
 * Convert RGB to HSL (each channel 0-255 in, degrees/percent out).
 * @param {{r:number,g:number,b:number}} rgb
 * @returns {{ h: number, s: number, l: number }}
 */
function rgbToHsl({ r, g, b }) {
    r /= 255; g /= 255; b /= 255;
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    let h = 0, s = 0;
    const l = (max + min) / 2;
    if (max !== min) {
        const d = max - min;
        s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        switch (max) {
            case r: h = (g - b) / d + (g < b ? 6 : 0); break;
            case g: h = (b - r) / d + 2; break;
            default: h = (r - g) / d + 4; break;
        }
        h /= 6;
    }
    return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
}

module.exports = {
    data: new SlashCommandBuilder()
        .setName('colorinfo')
        .setDescription('Inspect a hex color (RGB, HSL, preview)')
        .addStringOption(option =>
            option.setName('hex')
                .setDescription('Hex color, e.g. #5865F2 or f00')
                .setRequired(true)),

    async execute(interaction) {
        const hex = normalizeHex(interaction.options.getString('hex'));
        if (!hex) {
            return interaction.reply({
                content: '❌ Invalid hex color. Try formats like `#5865F2`, `5865F2`, or `f00`.',
                ephemeral: true
            });
        }

        const rgb = hexToRgb(hex);
        const hsl = rgbToHsl(rgb);
        const intValue = parseInt(hex, 16);

        const embed = new EmbedBuilder()
            .setTitle(`🎨 #${hex.toUpperCase()}`)
            .setColor(intValue)
            .addFields(
                { name: 'HEX', value: `\`#${hex.toUpperCase()}\``, inline: true },
                { name: 'RGB', value: `\`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})\``, inline: true },
                { name: 'HSL', value: `\`hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)\``, inline: true },
                { name: 'Integer', value: `\`${intValue}\``, inline: true }
            )
            // A tiny solid-color image generated by the dummyimage service.
            .setThumbnail(`https://dummyimage.com/200x200/${hex}/${hex}.png`)
            .setFooter({ text: `Requested by ${interaction.user.tag}` });

        await interaction.reply({ embeds: [embed] });
    }
};

// End of file: colorinfo.js
