'use strict';

/**
 * Staff Dashboard — web server.
 *
 * Flow:
 *   1. Staff visits the site and clicks "Login with Discord" (OAuth2).
 *   2. After login we create a ServerSelection record (status: awaiting).
 *   3. The BOT sees that record and DMs the user with two buttons (the 2 servers).
 *   4. User clicks a button -> bot writes the chosen guild back to the record.
 *   5. Dashboard unlocks; staff can run whitelisted commands into that guild.
 *
 * The bot and this server never talk directly — they share MongoDB collections.
 */

const path = require('node:path');
const fs = require('node:fs');
const express = require('express');
const session = require('express-session');
const MongoStore = require('connect-mongo');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');

const config = require('./src/config');
const db = require('./src/db');
const authRoutes = require('./src/routes/auth');
const apiRoutes = require('./src/routes/api');
const { requireAuth, requireServer } = require('./src/middleware');

const app = express();
const PUBLIC_DIR = path.join(__dirname, 'public');

app.set('trust proxy', 1); // behind a reverse proxy / load balancer in production

app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ["'self'"],
        styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
        fontSrc: ["'self'", 'https://fonts.gstatic.com'],
        imgSrc: ["'self'", 'data:', 'https://cdn.discordapp.com'],
        connectSrc: ["'self'"],
      },
    },
  }),
);

app.use(express.json({ limit: '64kb' }));
app.use(express.urlencoded({ extended: true }));

app.use(
  session({
    name: 'staff.sid',
    secret: config.sessionSecret,
    resave: false,
    saveUninitialized: false,
    store: config.mongoUri
      ? MongoStore.create({ mongoUrl: config.mongoUri, collectionName: 'dashboard_sessions' })
      : undefined,
    cookie: {
      httpOnly: true,
      sameSite: 'lax',
      secure: config.baseUrl.startsWith('https://'),
      maxAge: 1000 * 60 * 60 * 12, // 12h
    },
  }),
);

// Throttle the command endpoint so a logged-in user can't spam the bot.
const commandLimiter = rateLimit({ windowMs: 60 * 1000, max: 20, standardHeaders: true });

app.use('/auth', authRoutes);
app.use('/api/command', commandLimiter);
app.use('/api', apiRoutes);

// Static assets (css/js/images).
app.use('/static', express.static(path.join(PUBLIC_DIR), { index: false }));

// --- Pages ---
app.get('/', (req, res) => {
  if (req.session.user) return res.redirect('/select');
  res.sendFile(path.join(PUBLIC_DIR, 'index.html'));
});

app.get('/select', requireAuth, (req, res) => {
  if (req.session.selectedGuildId) return res.redirect('/dashboard');
  res.sendFile(path.join(PUBLIC_DIR, 'select.html'));
});

app.get('/dashboard', requireAuth, requireServer, (req, res) => {
  res.sendFile(path.join(PUBLIC_DIR, 'dashboard.html'));
});

// Staff handbook (generated by tools/generate-handbook.js). Public reference,
// linked from the login page, so no auth required.
app.get('/handbook', (req, res) => {
  const file = path.join(PUBLIC_DIR, 'handbook.html');
  if (!fs.existsSync(file)) {
    return res.status(404).send('Handbook not generated yet. Run: npm run handbook');
  }
  res.sendFile(file);
});

// Health endpoint (the Go microservice pings this).
app.get('/healthz', (req, res) => {
  res.json({
    ok: true,
    service: 'staff-dashboard',
    configured: config.isConfigured(),
    mongo: db.mongoose.connection.readyState === 1,
    uptime: process.uptime(),
    time: new Date().toISOString(),
  });
});

app.use((req, res) => res.status(404).sendFile(path.join(PUBLIC_DIR, 'index.html')));

async function start() {
  if (config.mongoUri) {
    try {
      await db.connect(config.mongoUri);
      console.log('[dashboard] connected to MongoDB');
    } catch (err) {
      console.error('[dashboard] MongoDB connection failed:', err.message);
    }
  } else {
    console.warn('[dashboard] MONGO_URI not set — sessions will be in-memory and the bot bridge will not work.');
  }

  app.listen(config.port, () => {
    console.log('========================================================');
    console.log(`  Staff Dashboard listening on port ${config.port}`);
    console.log(`  Public URL:    ${config.baseUrl}`);
    console.log(`  OAuth redirect: ${config.discord.redirectUri}`);
    console.log(`  Configured:     ${config.isConfigured() ? 'yes' : 'NO — set .env values'}`);
    console.log('========================================================');
  });
}

start();

module.exports = app;
